name: myalice
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  pusher_client: ^2.0.0
  dio: ^4.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.7
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.0.0
  sqflite: ^2.0.0+3
  scrollable_positioned_list: ^0.1.10
  smart_select: ^4.3.2
  modal_bottom_sheet: ^2.0.0
  multi_select_flutter: ^4.0.0
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  dropdown_search: ^0.6.3
  image_picker: ^0.8.4 
  package_info: ^2.0.2
  expandable: ^5.0.1
  connectivity: ^3.0.6
  url_launcher: ^6.0.12
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/launch_icon/


